version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3005:3000
    volumes:
      - ./:/code
      - ./repos:/repos
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:6
